### ISSUE TITLE
Icono bloqueo empresa en cliente

### ISSUE THREAD

**Issue by r-next** [cartoneria/Cotizar#4]
Se debe agregar el puntero bloqueado en el campo empresa para los modulos:

Asesores --> Crear
Asesores --> Editar
Clientes --> Crear
Clientes --> Editar

**Comment by efrainx3** [comment]
Se ajusta select empresas en Asesor[Crear y editar] y Cliente[Crear y editar].

**Comment by r-next** [comment]
aun se presenta el error en crear cliente, agregar tambien en proveedor crear y editar

**Comment by efrainx3** [comment]
Se había eliminado la clase del archivo css.
Se crea nuevamente la clase.
